### ISSUE TITLE
Turn Printer on and off

### ISSUE THREAD

**Issue by mrp192** [MoonshineSG/OctoPrint-Mobile#12]
Hello,
 First I wanna say I love that there is an App I can use instead of having to do the web interface on my phone.

Now I have a relay setup that is controlled in octoprint to turn my printer on and off. It would be great if I was able to use that through the app! 
![power](https://cloud.githubusercontent.com/assets/18508896/21070701/c5c9ec84-be3f-11e6-9885-0c610fe6522a.JPG)

**Comment by MoonshineSG** [comment]
assuming you use GPIO to control your relay, you can!!!!
but... you need to install another plugin, called "Octoprint Switch" .  See https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/settings.ini#printer-commands-and-settings

Just a word of warning, the Switch plugin is not super well documented.

**Comment by mrp192** [comment]
I do have GPIO installed. I have been doing it this way for awhile. I just didnt see an option in Nautilus.

**Comment by MoonshineSG** [comment]
hahaha....the $0.99 is just to cover the Apple license (and a couple of beers) not to get rich :D 

glad you like it! Do leave a positive feedback on AppStore, as so far only people who don't like it - how can they!!! -  have left feedback ...

**Comment by mrp192** [comment]
done.

**Comment by MoonshineSG** [comment]
Thanks.

**Comment by MoonshineSG** [comment]
Let me know if you need help with "Swithc"
