### ISSUE TITLE
Plugin requires IOS app

### ISSUE THREAD

**Issue by pyjamasam** [MoonshineSG/OctoPrint-Mobile#13]
Not so much an issue, but just something I think should be stated in all the plugin descriptions, both here on github and in the octoprint plugin repository.

This plugin requires the IOS app to run.  The plugin only activates when the user agent starts with "Nautilus".

Again, this isn't a criticism of this plugin/mobile app.  Its very nice.  I like it a lot.  I just want to make sure other people who look into it realize that the app is required (Ya I get that the apps source code is also available here, and you can download and build it on your own - as I did), I just feel it needs to be more clear that you can't just get to this plugin's UI via a mobile browser.

**Comment by MoonshineSG** [comment]
Firstly, I'm glad you like it!
Fair point. I will update the descriptions to highlight the app requirement
