### ISSUE TITLE
Multiple printers - question

### ISSUE THREAD

**Issue by Radekva** [MoonshineSG/OctoPrint-Mobile#14]
It is not issue but only question. It is able to work comfortably with two or more printers?

**Comment by MoonshineSG** [comment]
Sadly, it doesn't and I can't see how this can be easily implemented.

**Comment by pyjamasam** [comment]
I think adding a simple switching overlay. Like tabs or some other kinda simpler switching mechanism would do it. 

Really you just have to sent the web view to another URL. 

Loving the setting out of the settings app and making them in app would be a first step. You'll have more flexibility with respect to storing multiple instances of url's and API keys. 

But it just boils down to switching the base URL for all the calls.  Now your on a new printer. :-)

**Comment by pyjamasam** [comment]
Cause I can't sort out how to edit a comment on my phone....

When I say switching overlay it's somthing that would be implemented in the objective-c code of the app. Not on the web side. 

Chris.

**Comment by MoonshineSG** [comment]
There are a few other issues to be handled if multi printer needs to be supported, but nothing too complicated.
There is just a matter of finding the time for it...

**Comment by Radekva** [comment]
So later it would support. Not in the near future?

**Comment by MoonshineSG** [comment]
I am not saying it will. Not that it won't. Depends if there is interest (I'll leave this open so anyone can express interest). It would not make sense to develop it for one single users. 

I'll asses the effort and see if my time permits. It's also worth noting that I only have one printer (and I don't foresee buying/building another one in the near future (that is, if I wana stay married! :) )
