### ISSUE TITLE
Feature request: Ability to select a file to print 

### ISSUE THREAD

**Issue by mskressin** [MoonshineSG/OctoPrint-Mobile#15]
Would it be possible to add the capability to select a file to print instead of just the last file? It is very easy to load multiple files to print onto the OctoPi's memory card. It would be very nice to use Nautilus to select a particular file to print.

**Comment by MoonshineSG** [comment]
Nautilus was not intended to be a full replacement for OctoPrint and it's trying to keep the user interface at a minimum. Adding a file selection is not on the planned enhancements.
