### ISSUE TITLE
IOS App does not work still

### ISSUE THREAD

**Issue by macrhino** [MoonshineSG/OctoPrint-Mobile#16]
As well. Configured. API key is there. There is a connection but nothing. There is a screen shot attached, 

The plugin is installed and shows up in Plugin Manager. 

![img_5110](https://cloud.githubusercontent.com/assets/11146789/21453840/5214771c-c8e1-11e6-8c35-664f2c10d9bc.PNG)

**Comment by MoonshineSG** [comment]
what do the logs show ? screen shot is from the iphone ?

**Comment by macrhino** [comment]
Which logs? The plugin logs?

The URL is simple. When it is wrong, the program complains. Then the program notices that my API key was wrong (impossible if the URL was incorrect). I corrected the API key and I get a black screen everytime.

**Comment by macrhino** [comment]
OK I know where the black screen comes from. It is the camera connected to the Octoprint. This is all that I get, just the camera.  No way to control anything or to make the camera picture go away.

**Comment by MoonshineSG** [comment]
Oh.... ok. That happens when the connection is "external". What is the URL for your OctoPrint? Can you send the OctoPrint logs, to see why that happens ?

**Comment by macrhino** [comment]
[octoprint.log.html.zip](https://github.com/MoonshineSG/OctoPrint-Mobile/files/672186/octoprint.log.html.zip)

**Comment by MoonshineSG** [comment]
Merry Christmas!

By using a dynamic dns, you access your octoprint from the external network and therefor nautilus switches from full interface to pure webcam monitoring. 
I will add an option in the Nautilus settings to give the option to turn this function off, so that even from "outside" you will see the full interface. 

Give me a couple of days.

**Comment by MoonshineSG** [comment]
@macrhino release 1.6.2 should solve your problem.

**Comment by MoonshineSG** [comment]
Everything ok now?
