### ISSUE TITLE
Non-0 axis minimums?

### ISSUE THREAD

**Issue by KriLL3** [MoonshineSG/OctoPrint-Mobile#17]
Hi there, like the look of this plugin/app but I'm using non-0 minimum axis locations, my axis extends outside my bed so after homing I'm at X-22, Y-2, Z-1 in the configuration there is

x_max = 200
y_max = 200
z_max = 200

But no min values, not been brave enough to try adding:

x_min = -22
y_min = -2
z_min = -1

Does it work if I add them or is that a feature not yet implemented?

**Comment by MoonshineSG** [comment]
yes, you can add those values in the `[profile]` section and then 
change in the `[action]` section change the 

```
goto_x_min = G1 X0 {{fast}}
goto_y_min = G1 Y0 {{fast}}
goto_z_min = G1 Z0 {{medium}}
```

to 

```
goto_x_min = G1 X{{x_min}} {{fast}}
goto_y_min = G1 Y{{y_min}} {{fast}}
goto_z_min = G1 Z{{z_min}} {{medium}}
```

There are some other places where the default settings use `0` as min. See `goto_back_left` and `goto_front_left`. You can replace those zeros with the `*_min` variables.
