### ISSUE TITLE
Mobile app does not work

### ISSUE THREAD

**Issue by clarkewd** [MoonshineSG/OctoPrint-Mobile#19]
Downloaded app from iTunes - but it's stuck after opening it on iPhone.

> Before you can use this application, the "Nautilus" plugin needs to be installed on OctoPrint and you need to setup the OctoPrint server URL and the API KEY in the settings of this app.

Screenshot:

<img src="http://imagizer.imageshack.com/img923/4906/maK5fb.jpg" alt="IMG_5793.jpg" />

How do I get to the "settings" ?

**Comment by 1n5aN1aC** [comment]
You go to the 'settings' app on your phone.

Scroll down near the bottom, and there will be a link 'nautilus'

**Comment by MoonshineSG** [comment]
I guess you found it. Unfortunately, the end of the message did not fit into the screen.  It reads "(shake to load the app settings)".... :D 
I'll change the font size in the next release.
