### ISSUE TITLE
Request times out

### ISSUE THREAD

**Issue by joeynuggetz** [MoonshineSG/OctoPrint-Mobile#30]
I've tried adding both the IP address for the URL of my octo instance as well as http://octoprint.local and connection always times out. API key is also set. What could be the issue?

**Comment by MoonshineSG** [comment]
I assume you're on local wifi ... can you connect to the OctoPrint using safari ? (on the ios device) ?

**Comment by joeynuggetz** [comment]
That led me in the right direction. Didn't have wifi enabled like a
bonehead. Thanks!
