### ISSUE TITLE
Old version problem with IOS app

### ISSUE THREAD

**Issue by jotaperamez** [MoonshineSG/OctoPrint-Mobile#31]
I was checking Nautilus app 1.9 and when i tried to start it, it show me a message "Your version of Nautilus is too older". Some suggestion?

thanks

**Comment by MoonshineSG** [comment]
Please read https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/Update

**Comment by jotaperamez** [comment]
i did, my version of Nautilus is 1.9 but same problem

**Comment by MoonshineSG** [comment]
1. check what does `http://YOUR_URL_HERE/plugin/nautilus/static/js/version.js` shows. If it does not show 1.9, try to manually re-install the plugin.

2. try to "kill" the iOS app and start it again.  (cache? - shouldn't be)

3. what OS are you running OctoPrint on ?

**Comment by jotaperamez** [comment]
just reinstall iOS app and works! :) ty

**Comment by MoonshineSG** [comment]
strange. but glad it works. enjoy.
