### ISSUE TITLE
the request timed out

### ISSUE THREAD

**Issue by g60leigh** [MoonshineSG/OctoPrint-Mobile#32]
hi
running nautilus on both my iPhone 7 and iPad air. set up instructions followed 
but always get the request timed out error

**Comment by MoonshineSG** [comment]
can you access your octoprint using the same url on safari on the same iphone 7 and ipad air ? 

via wifi or over a3G/4G connection ?

**Comment by g60leigh** [comment]
Yes I can access it via wifi and web on both my phone and iPad without any issue.

**Comment by MoonshineSG** [comment]
couple of things you can try:

- shake the device - this will force a page reload.

if that doesn't work, try to "kill" the ios app (double home and sweep), then reopen.

let me know if it helps.

**Comment by MoonshineSG** [comment]
did you managed to get it working ?

**Comment by g60leigh** [comment]
I have it partially working. 

Can get it going on the phone but won't work on the iPad at all? I'm just using the web interface for octoprint itself as it works every time and can trust it. 

Not confident that this will work and not fail part way through a process. 

Thanks
Leigh

**Comment by MoonshineSG** [comment]
I don't have an iPad Air to test, but I don't see why it should be different from others. I have an iPad 2 and an iPad mini... both work ok.

**Comment by nowkillkennys** [comment]
updated today and it has stoped octoprint can't access t

**Comment by MoonshineSG** [comment]
Hmmmm.... the update had no "fix" for that... strange!
