### ISSUE TITLE
Please add the print speed to the control

### ISSUE THREAD

**Issue by stofakiller** [MoonshineSG/OctoPrint-Mobile#33]
Hi,

Please add the print speed to the control, so you can set it how fast it should print...

**Comment by MoonshineSG** [comment]
all the movement buttons have the `F` parameter set via the config file or via the octoprint printer profile.

**Comment by MoonshineSG** [comment]
oh... you meant support for "dynamic" speed change (M220) ?

**Comment by MoonshineSG** [comment]
done. see release 1.10
