### ISSUE TITLE
App refuses to connect

### ISSUE THREAD

**Issue by DonArkon** [MoonshineSG/OctoPrint-Mobile#34]
The App refuses to connect with following message:

`The certificate for this server is invalid. You might be connecting to a server that is pretending to be "XXX.XXX.XXX.XXX" which could put your confidential information at risk` (X'd out the IP-Adress)

**Comment by MoonshineSG** [comment]
https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/SSL-Error
