### ISSUE TITLE
better way of selecting prints

### ISSUE THREAD

**Issue by Austinthemighty** [MoonshineSG/OctoPrint-Mobile#38]
There needs to be a better way of selecting prints other than selecting the last uploaded print.

**Comment by MoonshineSG** [comment]
it's supposed to be only a simplified UI for mobile not a full replacement for OctoPrint...

**Comment by Austinthemighty** [comment]
I get that but the last uploaded part does not always work and it would be a nice to select what you want to print, also i find the app a lot more reliable than the web interface

**Comment by MoonshineSG** [comment]
Reopening this as a reminder that there's interest and in the limit of my time and if I find an easy to implement solution (I hate to think about folders and other functions that might need to be added) I will consider to implement it...

**Comment by paulobnc** [comment]
this would definitely be nice. The other octoprint app has it where you can choose the file but has absolutely nothing else which is even worse

**Comment by MoonshineSG** [comment]
coming soon... (together with notifications! :D)

**Comment by 1n5aN1aC** [comment]
NOTIFICATIONS?!

(Incredibly excited for that)

**Comment by MoonshineSG** [comment]
yup.. those are fully working now... might release it separately if  proves to be stable enough... 
oh.. and i need to find a unique sound for it :D

**Comment by MoonshineSG** [comment]
see release 1.15

**Comment by Austinthemighty** [comment]
Thanks, this has greatly improved the app
