### ISSUE TITLE
Only camera after new octoprint

### ISSUE THREAD

**Issue by stofakiller** [MoonshineSG/OctoPrint-Mobile#39]
My card got corrupted, so i had to flash a new octoprint and got a new API key, but now i can only see the camera in the IOS app. Tried to reboot the phone, kill the app etc... Only camera is working...

**Comment by MoonshineSG** [comment]
That means you're accessing the server from external IP. You can force the full UI even for external with a switch under the Nautilus plugin settings.

**Comment by stofakiller** [comment]
Ahh 😊

Found it, i was looking under the API. I works 😊
