### ISSUE TITLE
Cannot change IP

### ISSUE THREAD

**Issue by NeoTrace82** [MoonshineSG/OctoPrint-Mobile#40]
The IP Adresse of my Printer has been changed, as i did swap my router.
How do i change the IP, cant find anything.

**Comment by MoonshineSG** [comment]
which version of the iOS app  do you use ?

**Comment by NeoTrace82** [comment]
2.0 did the update yesterday

**Comment by MoonshineSG** [comment]
Yes, for 2.0 the settings have moved from the Settings app to the application itself... 
Swipe right from the (screen edge) to get to the screen with all the printers (https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/iOS-App#printer-selection) and then long tap on the printer to access the Edit screen...

**Comment by NeoTrace82** [comment]
long tap, did the trick

but now if i change the URL to "http://192.168.0.146:50" it does highlight red if i press Save

**Comment by MoonshineSG** [comment]
hmmm... there's a URL check ... the port is the one that fails... 
unfortunately to fix this I need to submit a new app to apple.. gona take a couple of days...

**Comment by NeoTrace82** [comment]
ah okay, nevermind
ill have time to wait till you fixed this

thanks for your instant and awesome support :)

**Comment by MoonshineSG** [comment]
No worries... just put some stars on the AppStore ;)

**Comment by MoonshineSG** [comment]
version 2.0.1 which has the fix for the url check has been submitted to Apple.  Now we wait....

**Comment by aholesen** [comment]
I have purchased additional printers but I cannot change my IP for the original printer or add another printer. It fails at the IP adress even though it is correct. Looking forward to 2.0.1 version.

**Comment by MoonshineSG** [comment]
@aholesen what is your URL format?

**Comment by aholesen** [comment]
http://MYNAME.synology.me:81 and http://MYNAME.synology.me:82

New logo/icon is nice BTW.

**Comment by MoonshineSG** [comment]
Ah... it's the port again... sorry about that... I completely forgot testing with port... 
Apple taking their time with the review... 

Thanks! I like the new logo too... :)

**Comment by MoonshineSG** [comment]
The fix is out.

**Comment by aholesen** [comment]
And it is working fine now - thank you.
