### ISSUE TITLE
Mirrored configuration

### ISSUE THREAD

**Issue by richgain** [MoonshineSG/OctoPrint-Mobile#41]
Regarding:
> 9 - Preselect the extruder to which the load/unload extrude/retract actions apply.
> Not configurable. It will send T0 for "Left" and T1 for "Right"

The E3D BigBox Hybrid Dual is frequently built in a mirrored configuration.
https://wiki.e3d-online.com/wiki/BigBox_Version_Overview#BigBox_Dual_Hybrid_Titan_Mirrored

This means that I need Extruder 0 (right):   Extruder 1 (left)  for correct configuration.

**Comment by MoonshineSG** [comment]
Easy fix. Will make them configurable.
Give me a couple of days.

**Comment by MoonshineSG** [comment]
new release supports this.
