### ISSUE TITLE
Invalid APIKEY

### ISSUE THREAD

**Issue by stofakiller** [MoonshineSG/OctoPrint-Mobile#42]
Hi,

I have updated both IOS app (2.0.1) and Nautilus 1.12, i have 2 printers and i get invalid APIKEY on both, i have use the camera to get the apikey into the app

**Comment by MoonshineSG** [comment]
The qr scanned key matches the api key in OctoPrint?

**Comment by MoonshineSG** [comment]
And you only have one printer, so there can't be a case of mixed URL/api key ?

**Comment by stofakiller** [comment]
Hmm, strange, i must have mixed the 2 API-keys, it works now

**Comment by MoonshineSG** [comment]
gave me palpitations.. :D 
the app had  intermittent  "invalid apikey" issue which has been fixed.. you scared me that somehow it sneaked back into the latest release...   
i'm glad it was just a mistake... enjoy the multi printer version!
