### ISSUE TITLE
App Only shows Video

### ISSUE THREAD

**Issue by dmward1978** [MoonshineSG/OctoPrint-Mobile#43]
When the App is opened it goes to the full screen video and wont down zoom to show the left hand tool bar.

**Comment by MoonshineSG** [comment]
you are accessing it from external IP. The default behaviour is that th eapp will switch to full screen unless you disable "External access show only webcam" in the OctoPrint settings (under Nautilus plugin)

see also https://github.com/MoonshineSG/OctoPrint-Mobile/issues/39

**Comment by dmward1978** [comment]
That fixed it!! Thanks!
