### ISSUE TITLE
Request times out

### ISSUE THREAD

**Issue by Pappasunrise** [MoonshineSG/OctoPrint-Mobile#47]
The new version doesn't seem to fix my problem unfortunately. I get a very long loading screen followed by "the request timed out" .

**Comment by MoonshineSG** [comment]
i see... using the browser on your phone, can you access the same url you configured on the app ?

**Comment by Pappasunrise** [comment]
What URL are you referring to?

**Comment by MoonshineSG** [comment]
the one you used when you configured your printer in Nautilus.. You had to enter a Name, URL, Api-Key... I'm referring to the URL

**Comment by Pappasunrise** [comment]
I downloaded the nautilus plugin on octoprint, I download the app on my phone and when it asks for the API I use the QR code and I select the local, non iCloud option, and then it loads until it fails. Is there something else I need to do first?

Sent with my iPhone

**Comment by MoonshineSG** [comment]
yes, you need to configure the URL of your printer... 
how do you access octoprint on your browser ?

**Comment by Pappasunrise** [comment]
Just with the octoprint.local http

Sent with my iPhone

**Comment by MoonshineSG** [comment]
> I select the local

by that you mean you left it as `http://octoprint.local` ? is that what you type in your browser ?

**Comment by MoonshineSG** [comment]
and your iphone is on  the same network/wifi as the printer ?

**Comment by Pappasunrise** [comment]
Yes. Same network. 

Sent with my iPhone

**Comment by MoonshineSG** [comment]
and if you type `http://octoprint.local` on  the browser on your iphone you can see the octoprint UI ?

**Comment by Pappasunrise** [comment]
No I just figured out I need it to be http://octopi.local

Sent with my iPhone

**Comment by MoonshineSG** [comment]
oh.... so `octopi` not `octoprint`  ?

**Comment by Pappasunrise** [comment]
Yes. 

Sent with my iPhone

**Comment by MoonshineSG** [comment]
so now it works ?

**Comment by Pappasunrise** [comment]
Mostly. Some of the buttons in the app don't do anything it seems like. I hit the home buttons and nothing happens.

Sent with my iPhone

**Comment by MoonshineSG** [comment]
one step at the time...  :D

whats your printer model ? standard gcode ? the code sent by every button can be individually configured in the OctoPrint settings... have a look if your printer is non standard...  turn on the debug and look at the logs.. you can also see the OctoPrint terminal for clues of what it gets sent and why it may not work...

**Comment by Pappasunrise** [comment]
The printer I'm using now is a creality CR-10. It uses standard g-code. 

Sent with my iPhone

**Comment by MoonshineSG** [comment]
just check the OctoPrint terminal and work out what doesn't work and do the appropriate changes on the settings if needed...

**Comment by Pappasunrise** [comment]
It moves when I move it on the app, but it won't home. If I hit the home button from the app the terminal shows nothing. 

Sent with my iPhone

**Comment by MoonshineSG** [comment]
check the settings .. it should send G28

**Comment by Pappasunrise** [comment]
None of the buttons on the top work

Sent with my iPhone

**Comment by MoonshineSG** [comment]
which ones ?

**Comment by Pappasunrise** [comment]
All of these

Sent with my iPhone

**Comment by MoonshineSG** [comment]
if you're not being specific there is no way for me to help you.

**Comment by Pappasunrise** [comment]
I attached a picture. I circled the buttons that don't do anything.

Sent with my iPhone

**Comment by MoonshineSG** [comment]
i guess smth went wrong with the attachment... i cant see it...

**Comment by Pappasunrise** [comment]
Alright well it's all of the axis homing buttons, as well as the menu button to the right of those

Sent with my iPhone

**Comment by Pappasunrise** [comment]
Sent with my iPhone

**Comment by MoonshineSG** [comment]
still no picture.. but nevermind...

you can try the following:

- ssh into your RPi... 
- remove the file `/home/pi/.octoprint/data/nautilus/settings.ini` (if will be recreated)
- restart OctoPrint (or reboot the RPi)

and try again...

**Comment by MoonshineSG** [comment]
did you manage to get it fixed ?
