### ISSUE TITLE
Stuck on camera screen, won't show menu

### ISSUE THREAD

**Issue by rmogull** [MoonshineSG/OctoPrint-Mobile#48]
On an iPhone 7+ the app will connect to OctoPrint but only shows the camera feed. Tapping on the screen or resizing the image still doesn't show the menu to access other parts of the system.

**Comment by MoonshineSG** [comment]
See https://github.com/MoonshineSG/OctoPrint-Mobile/issues/43

**Comment by rmogull** [comment]
Ugh... sorry.
