### ISSUE TITLE
The Request Timed Out

### ISSUE THREAD

**Issue by jagvent** [MoonshineSG/OctoPrint-Mobile#49]
I've installed the plugin, installed the iOS app, applied the API key (and make sure it was enabled).

From iOS, I only get "Loading......" then a screen with 'The Request Timed Out'.  

Any ideas?

**Comment by MoonshineSG** [comment]
read this carefully and make sure you the highlighted  test works. 
https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/iOS-App#addedit-printer-configuration

**Comment by jagvent** [comment]
Oops.  Was trying to load from the default octoprint.local instead of
octopi.local.  I had to remove the iOS app and reinstall to reconfigure
because couldn't get out of the "Loading" screen.

**Comment by MoonshineSG** [comment]
there's a timeout of 2 min... :D 
you can also "kill" the app... but reinstall works as well :D

**Comment by jagvent** [comment]
After the time out message, it went back to loading message and looped. When I "killed" the app and restarted, it went right back to loading without opportunity to change the configuration. The only solution was to uninstall.

**Comment by MoonshineSG** [comment]
you;re right. it would go back to retry.... swipe right is the only way out...
(not critical, to be fixed in the next release)
