### ISSUE TITLE
Numbers and - not allowed as Hostnamen?

### ISSUE THREAD

**Issue by Crypton72** [MoonshineSG/OctoPrint-Mobile#50]
I've setup octopi to the hostname octopi-aneta2
Neither the hyphen (?) nor the number seem to be valid for Nautilus. Although those are allowed characters for hostnames.

**Comment by MoonshineSG** [comment]
The url check is "http(?:s)?://((?:[\\p{L}a-zA-Z0-9\\-]+.){1,}(?:[\\p{L}a-zA-Z]{2,})|(?:[0-9\\-]+.){3}(?:[0-9\\-]+){1})(:\\d{2,})?(/(?:\\S*))?" so both numbers and hyphen is allowed ...

**Comment by MoonshineSG** [comment]
Oh... probably you need a “.local” a single word, is not a valid hostname.

**Comment by MoonshineSG** [comment]
did you managed to get this working ?
