### ISSUE TITLE
Video stream not working

### ISSUE THREAD

**Issue by dvilo** [MoonshineSG/OctoPrint-Mobile#52]
I am using IP webcam and am able to view stream on iPhone from Octoprint/control and directly from IP webcam phone.

From within Nautilus I sometimes immediately get "Sorry, camera is not available.", other times it tries to load for about 20 seconds before the message is displayed. I have never been able to load the stream, even after reboots of both phone and pi.

Octoprint stream URL is set to http://192.168.1.xxx:8080/video (IP Webcam default streaming URL).

Any ideas on how to get the stream working?

**Comment by MoonshineSG** [comment]
The video stream url is taken from octoprint settings .

**Comment by dvilo** [comment]
Is any formatting done to the URL? Since stream is working in Octoprint it seems odd that it does not load in Nautilus.

**Comment by MoonshineSG** [comment]
No formatting is done. Simply taken from the settings. Can you access it on the octoprint on the iPhone?

**Comment by dvilo** [comment]
Yes, octoprint on iPhone is ok.

**Comment by MoonshineSG** [comment]
Strange. 
I am on holiday now but i’ll check next week when I get back home. 
Meanwhile can you have a look at the logs and see if you can spot any error messages?

**Comment by dvilo** [comment]
Further info: stream ratio is 4:3, could this have any unwanted effects?

**Comment by dvilo** [comment]
Thanks. I will keep you posted on my findings.

**Comment by MoonshineSG** [comment]
Ratio would give you a distorted image in the worst scenario...

**Comment by MoonshineSG** [comment]
is the url properly setup in the OctoPrint ?

**Comment by MoonshineSG** [comment]
did you managed to get this working ?
