### ISSUE TITLE
iOS 11 Beta (15A5327g)

### ISSUE THREAD

**Issue by McFly99** [MoonshineSG/OctoPrint-Mobile#53]
Camera viewing has stopped working on iOS 11. Looks like something in the video libraries has changed. It very quickly flickers, yet it works On the web interface well and worked right before the upgrade.

**Comment by McFly99** [comment]
Correction, reloaded app and now it flashes the loading screen between frames.

I can confirm it does not do this on the Octo app to the same server.

**Comment by MoonshineSG** [comment]
Yes, I am aware of the problem. Looking for a solution and hopefully it will be out with ios11

**Comment by MoonshineSG** [comment]
beta 5 seams to have solved the flickering...
