### ISSUE TITLE
Self signed SSL?

### ISSUE THREAD

**Issue by gitterdoneplease** [MoonshineSG/OctoPrint-Mobile#54]
I get a message about certificate not valid, etc., but cannot bypass. Is this a supported config?

**Comment by MoonshineSG** [comment]
See https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/SSL-Error

**Comment by MoonshineSG** [comment]
I suggest you use a free "proper" SSL cert if continues to be a problem for you.

**Comment by RaphPi** [comment]
Sorry but it doesn't work for me. I've made a new certificat and do the process ssl-error on iPhone but always the same request "the certificate for this server is invalid".

**Comment by MoonshineSG** [comment]
did you install the created cert on the iphone ?

**Comment by RaphPi** [comment]
Yes, it is installed and trusted.

**Comment by RaphPi** [comment]
It is a .crt file. I've followed the suggested link bellow.

**Comment by MoonshineSG** [comment]
is the certificate issued correctly, date, domain , etc  ?  and installed on the haproxy ? can you access - without error - the secured url from a browser -safari or chrome - on the iphone  ?

**Comment by gitterdoneplease** [comment]
@RaphPi I had the precise same issue. The only way to make it work is to create your own root, sign the cert and upload the root cert to phone and trust that.

**Comment by RaphPi** [comment]
@MoonshineSG on iPhone i can access to octoprint.

@gitterdoneplease That's what i do. Maybe i've made a mistake. What is the exact process for you ?

I've followed this tutorial to generate : https://github.com/PrusaMK2Users/MK2_Tips_and_Tricks/wiki/Generating-a-new-SSL-certificate-for-OctoPi

**Comment by RaphPi** [comment]
The strange things is that i receive notifications...

**Comment by gitterdoneplease** [comment]
A bit more complex. Something like this.

https://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority/

**Comment by MoonshineSG** [comment]
When you say that you can access octoprint, is that using https ? 
I have tested with self issued cert and with own root as well as proper ssl certificate. Once the iPhone recognizes the cert as trusted the Nautilus app does the same.

Alternatively you can get a proper ios recognized certificate. The ones from Let's Encrypt work great and are free.

Notifications are sent to the ios device by the apple servers and is independent from the way you access your printer.

**Comment by gitterdoneplease** [comment]
Let's Encrypt needs you to renew every 90 days. You run that on your Pi?

**Comment by MoonshineSG** [comment]
Yes, 90 days. But the renewal can be automated via a cron job. 
Since I found out about it, I replaced all my self issued certs with it and works like a charm!!

**Comment by gitterdoneplease** [comment]
Fair play sir. I'll look into it further. Seemed like a PITA.

**Comment by MoonshineSG** [comment]
once setup, you can (and will) forget about it... 

btw, if you only access the printer locally, you don't need https. 

If you access it from the internet, depending how you access it, the SSL cert would be needed on the proxy, if you use one.
If you just to a port redirect, then yes, the SSL cert should be on the RPi.

**Comment by RaphPi** [comment]
@MoonshineSG and @gitterdoneplease Thanks for your help but I'm stuck.
I've followed the tutorial and put the root and the device certificate on iPhone (See the device certificate on iPhone look good) but Nautilus don't want it.

Maybe you have the exactly command lignes I need to use. Is there something to change on haproxy.cfg ?

![img_0687](https://user-images.githubusercontent.com/11621323/29866465-c52d9542-8d78-11e7-9d09-722f46310e44.PNG)

**Comment by MoonshineSG** [comment]
the certificate you installed in ios is the root or the cert itself ? 

in my case (i use Let's Encrypt) I merged the `certificate.key` + `certificate.crt`  + `intermediate.crt ` into a single `certificate.pem` file and then the haproxy config has 

```
frontend public
        bind *:80
        bind 0.0.0.0:443 ssl crt /etc/ssl/certificate.pem

```

**Comment by RaphPi** [comment]
I install the root and the cert. If I put the cert without the root the cert is not trusted.
On the server I merge cert.key and cert.crt in snakeoil.pem. so I normally not need to changed the haproxy config file.

`frontend public
bind *:80
bind 0.0.0.0:443 ssl crt /etc/ssl/snakeoil.pem`

**Comment by MoonshineSG** [comment]
Sounds correct... not sure why is there an issue

**Comment by RaphPi** [comment]
With http connection it works. So it's really with the certificate.
Maybe the informations in the certificate are false. I don't know exactly what to put on domain. I try with the Internet IP+port or a name. it works on safari for the both. So what verifications do the apps that safari doesn't realize?

**Comment by MoonshineSG** [comment]
it's usually domain name but IP (no port) should work. the port is 443 almost alway ..
