### ISSUE TITLE
App opens, but no printer interface is loaded

### ISSUE THREAD

**Issue by caesarius** [MoonshineSG/OctoPrint-Mobile#55]
The app is loaded, but it freezes at the Loading page.

**Comment by MoonshineSG** [comment]
Please give more details about your setup. There is no way to know what could be wrong by saying "it freezes"

**Comment by caesarius** [comment]
The initial configuration is done, then it just freezes at the Loading screen… I'd love to give you more details, but I don't have anything else.
iPhone 6S MKQN2LZ/A, iOS 10.3.3 (14G60)

**Comment by caesarius** [comment]
Also, OctoPi attached to a Original Prusa MK2S.

**Comment by MoonshineSG** [comment]
http or https ? 
APIKEY setup ? 
the URL entered in the config page works on safari on the iphone ? (shoudl show OctoPrint UI)

**Comment by MoonshineSG** [comment]
nautilus plugin installed ?
errors in the octoprint logs ?

**Comment by caesarius** [comment]
- HTTP
- API Key setup
- It works on mi computer browser and iPhone browser
- Nautilus (1.17) plugin installed
- No errors

BUT nevermind, I was entering http://octoprint.local (the default URL on the configuration screen), instead http://octopi.local (my current setup).

So maybe there should be a way to view/edit the configuration instead launching it automatically. I uninstalled and reinstalled the app in order to do that.

**Comment by MoonshineSG** [comment]
there's no need to uninstall...  you can edit the configuration. Just swipe left to right from the left side of the screen (in landscape mode)
 
see https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/iOS-App#addedit-printer-configuration

**Comment by caesarius** [comment]
Thanks for the clarification. I would suggest making it explicit, having to read the manual for a core functionality is not ideal. Maybe a series of onboarding screens the first time the app is launched? My 5 cents.
