### ISSUE TITLE
constant loading screen

### ISSUE THREAD

**Issue by race12001** [MoonshineSG/OctoPrint-Mobile#56]
I installed the plugin on my iPhone 7 and my Pi but all it says is loading. I did get it to day timed out once but I can not get past the loading screen on the phone to set it up.

**Comment by MoonshineSG** [comment]
have a look at https://github.com/MoonshineSG/OctoPrint-Mobile/issues/55 and check out the "solution"

**Comment by MoonshineSG** [comment]
did you manage to get this working ?

**Comment by race12001** [comment]
I have not. I also have not had much time at the moment to test it, I've been moving / remodeling a house.

**Comment by MoonshineSG** [comment]
ok. anyway, I have a new version coming out for iOS 11 that handles better the timeouts and errors.

**Comment by MoonshineSG** [comment]
the new version is been out for a while. hopefully it solved your problem. let me know when you have time
