### ISSUE TITLE
Certificate for this server is invalid

### ISSUE THREAD

**Issue by NeoTrace82** [MoonshineSG/OctoPrint-Mobile#57]
Hi,

i didnt use Nautilus for 2 months, cause i didnt print anything when it was like 38 degrees Celsius :)
But i did power it on yesterday and wanted to Monitor via Nautilus and got the following message

"The certificate for this Server is invalid. You might be connecting to a Server that is pretending to be "192.168.0.145" which could put your configdential Information at risk."

Any advice what to do?

take care

**Comment by MoonshineSG** [comment]
Using https with self signed certificate and trying to connect via IP?

**Comment by MoonshineSG** [comment]
did yo managed to get it working ?

**Comment by MoonshineSG** [comment]
hopefully you got it working. I'll close it for now.
