### ISSUE TITLE
Name resolution not working

### ISSUE THREAD

**Issue by hutchyx** [MoonshineSG/OctoPrint-Mobile#59]
DNS Name resolution not working beyond the first 3 printers.   When setting up the fourth printer and beyond, it won't resolve the dns name, it'll only work via IP

**Comment by MoonshineSG** [comment]
DNS resolution is done by your network. Maybe smth wrong with the server name itself ?

**Comment by hutchyx** [comment]
I do get name resolution from other apps using the same name.  It's only started happening after ios11 update.

**Comment by MoonshineSG** [comment]
could be a typo error ?

**Comment by MoonshineSG** [comment]
what is the exact error message ?

**Comment by hutchyx** [comment]
Definitely not a typo.  I can copy and paste the same name to another app and get name resolution.  
It just flashes the back color of the octoprint url box to pink.   
I was incorrect earlier in saying it only happens beyond the first 3.   It seems to happen if I edit any of the existing profiles or try to add a new one.   
The existing profiles, unedited, work ok using names.

**Comment by MoonshineSG** [comment]
Ah... thats not the DNS... the app does a regex check to ensure a valid URL. 
If it fails for you, this is smth I need to fix. Can you tell me the url ? (change some words - for privacy -but keep the format - numbers, special characters, etc...)

**Comment by MoonshineSG** [comment]
and.. what version of the app are you using ?

**Comment by hutchyx** [comment]
Hyphens

**Comment by hutchyx** [comment]
Is there a way to see the version number? I have the most current from the iOS app store for iPhone

**Comment by MoonshineSG** [comment]
yup... tested on the latest version...failed. I'll have a fix and submit to apple... give me a few days. sorry.

**Comment by hutchyx** [comment]
Thanks! 
I thought I was losing my mind

**Comment by MoonshineSG** [comment]
version can be found in the iOS Settings / Nautilus

**Comment by MoonshineSG** [comment]
don't worry, you're sane!

**Comment by hutchyx** [comment]
2.1.2

**Comment by MoonshineSG** [comment]
New app is watch review. I left very basic checks so most (even rubbish) URL should pass. It will take a day or so for Apple to review the app.

**Comment by MoonshineSG** [comment]
New version is out. Update the app and try again.

**Comment by hutchyx** [comment]
Resolved
Thank you!

**Comment by MoonshineSG** [comment]
@hutchyx: positive (if justified) review/rating on AppStore is alway welcomed :D
