### ISSUE TITLE
Queueing of commands in XYZ-axis

### ISSUE THREAD

**Issue by Pipshag** [MoonshineSG/OctoPrint-Mobile#6]
**Queue commands for height.** 
I would want to be able to press Z-0.1 several times to achieve moving, for example, Z-0.3. As it stands now I think it just accepts Z-0.1 and then nothing else until the move is finished.

**Comment by MoonshineSG** [comment]
wouldnt 0.1 move super fast? 
Anyway, i believe it does accept comands even before the printer finishes the move... On both Movement and on Offset ...

**Comment by Pipshag** [comment]
Will re-test later.

**Comment by MoonshineSG** [comment]
did you get to try it ?
