### ISSUE TITLE
connectiosn server status

### ISSUE THREAD

**Issue by cpmorris** [MoonshineSG/OctoPrint-Mobile#60]
Has been working fine for weeks now my first install wont connect to the server and I cant change the config file.  I'm still able to control from the app but cant customize functions.  I tried uninstalling the plug in and reinstalling but that didn't fix it.  My other printer is working fine.

THanks

**Comment by MoonshineSG** [comment]
Sorry, i’m not sure what you mean

**Comment by cpmorris** [comment]
[image1.jpeg]

Sent from my iPhone

On Oct 19, 2017, at 8:17 PM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, i’m not sure what you mean

**Comment by MoonshineSG** [comment]
Try attaching the image again

**Comment by cpmorris** [comment]
[image1.jpeg]

Sent from my iPhone

On Oct 19, 2017, at 10:33 PM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


Try attaching the image again

**Comment by MoonshineSG** [comment]
Nope

**Comment by cpmorris** [comment]
When I click on nautilus under plug ins it says at the top: “notification server status:connection problem?”  And the config area is blank.  It had been working fine.  I’ve completely remove and installed the plug in and rebooted.

Sent from my iPhone

On Oct 20, 2017, at 12:36 AM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope

**Comment by MoonshineSG** [comment]
What version octoprint? I am away on holiday and haven’t check the plugin on the latest update... maybe smth is broken... 
can you see anything on the logs?
Your printer is connected to internet ?

**Comment by MoonshineSG** [comment]
How about when you use the iPhone app? Any problem? Or is just the settings page on octoprint has issues?

**Comment by cpmorris** [comment]
Both of my setups are running 1.3.5

Sent from my iPhone

On Oct 20, 2017, at 1:15 AM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


What version octoprint? I am away on holiday and haven’t check the plugin on the latest update... maybe smth is broken...
can you see anything on the logs?
Your printer is connected to internet ?

**Comment by MoonshineSG** [comment]
One works and one doesn’t?

**Comment by cpmorris** [comment]
Correct. Everything from the app works I just can’t customize the commands on the one that’s got the issue.

Sent from my iPhone

On Oct 20, 2017, at 1:58 AM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


One works and one doesn’t?

**Comment by MoonshineSG** [comment]
Strange. Both can connect to the internet ? 
Can you get the logs on the one that doesn’t work?
Any additional plugins running ?

**Comment by cpmorris** [comment]
Yes both have internet and same additional plug in. I’ll try to get the logs later this morning

Sent from my iPhone

On Oct 20, 2017, at 2:02 AM, ǝuıɥsuooɯ <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange. Both can connect to the internet ?
Can you get the logs on the one that doesn’t work?
Any additional plugins running ?

**Comment by MoonshineSG** [comment]
managed to get it working ?

**Comment by cpmorris** [comment]
Yes it is back to normal now.  Didn't do anything specific.

**Comment by MoonshineSG** [comment]
maybe it was just some network issue. I'll close this for now, but feel free to reopen if you face more problems.
