### ISSUE TITLE
Webcam Display in iOS App

### ISSUE THREAD

**Issue by digitaljunk** [MoonshineSG/OctoPrint-Mobile#61]
Cant get an network camera to work in the App.
Suggestions? 
iOS 11.1.2
OctoPrint 1.3.5
Nautilus 1.18
Stream URL: http://IP/video.cgi
on LAN/WIFI

**Comment by MoonshineSG** [comment]
Is it setup in OctoPrint ?
does it work in OctoPrint ? 
the `IP` is the same as the OctoPrint IP ?

**Comment by digitaljunk** [comment]
Yes, its in the octoprint settings.
Its running fine in octoprint. 
No, cam has different IP. The IP is on the same LAN and IP range.

**Comment by MoonshineSG** [comment]
so, the OctoPrint settings has `http://IP1/video.cgi`  setup and works well when accessed on a browser on `http://IP2`, but not on Nautilus ? Nautilus is setup to access  `http://IP2`. Is this right ?
 
Does the rest of UI works on Nautilus ? Any error message ("cam not available"?) or just an empty screen ?

**Comment by digitaljunk** [comment]
Thats correct. IPs are different.
"Sorry, Camera is not available." Error Message.

**Comment by MoonshineSG** [comment]
can you open `http://IP/video.cgi` from a **browser** on the iPhone ?

**Comment by digitaljunk** [comment]
Yes, it works in Safari.

**Comment by MoonshineSG** [comment]
thats normal, as it is streaming and it is constantly loading...

are you able to SSH to the machine where OctoPrint/Nautilkus is installed ?

**Comment by digitaljunk** [comment]
Yepp, but i need some sleep now. :( I am following this tomorrow again. :)

**Comment by MoonshineSG** [comment]
never mind the SSH... there will be a fix by the time you wake up.
update the plugins and it should be ok

**Comment by digitaljunk** [comment]
its fixed! Thank you for your awesome Support.

**Comment by MoonshineSG** [comment]
Youțre welcome. A positive rating/review on App Store would be much appreciated :D
