### ISSUE TITLE
[Request] Finish print notification

### ISSUE THREAD

**Issue by gamernjs** [MoonshineSG/OctoPrint-Mobile#65]
Hello,

I wasn’t sure where to post this. Would it be possible to have the app notify you when the print is finished? Or is that already a feature that I’ve overlooked? 

Thank you, 
- Noah

**Comment by MoonshineSG** [comment]
Absolutely. It's one of the nice features of Nautilus. 
See https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/Notifications for details. 
Post here if you have problems with it and I'll be happy to guide you in solving it....

**Comment by gamernjs** [comment]
Awesome! I figured I overlooked it. Thank you! Do you plan to add Apple Watch Support? I'd be happy to beta test it if so.

**Comment by MoonshineSG** [comment]
To be honest, I don't have such plans. I don't have one nor plan to get one - although I am a full apple ecosystem :D 
And it would be quite complicated with the multi printer. 
Sorry.
