### ISSUE TITLE
unable to "Buy more" in iOS app after 10 printers

### ISSUE THREAD

**Issue by hutchyx** [MoonshineSG/OctoPrint-Mobile#66]
I currently have 10 printers configured in the iOS app.  When I hit the "Buy more" button, I get a Purchase Error saying Sorry, there are no products available to purchase.  Is there any way to configure more than 10 printers?

**Comment by MoonshineSG** [comment]
not at this moment. give me a few days (I am traveling at this moment) and I'll add more.

**Comment by MoonshineSG** [comment]
Try now

**Comment by MoonshineSG** [comment]
Noticed that you made a purchase (must be you). Closing the issue
