### ISSUE TITLE
[Request] Print Percentage

### ISSUE THREAD

**Issue by mhodder** [MoonshineSG/OctoPrint-Mobile#68]
Awesome app, I use it as a local controller for my 3d printer. One thing that I would love to have is an actual completion percentage readout in addition to the green bar slider. I find that when I print from the printers SD card the completion percent is the thing I look at the most. when printing directly from octoprint that feature is missing. Your app has everything else needed except the completion percentage as a value.

Maybe replace the printing text with the actual completion percent
"Printing - 10.5%"
or
"10.5% complete"

awesome work, and with or without this feature this is my go to app.

Thanks

**Comment by MoonshineSG** [comment]
done.
