### ISSUE TITLE
Possibility to reverse axis (movement)

### ISSUE THREAD

**Issue by Pipshag** [MoonshineSG/OctoPrint-Mobile#7]
**Add a function to revert movement direction**
I'm running a BigBox from E3D where lowering the nozzle is actually pushing the bed up. This makes axis movements in Z-axis reversed. If there was a possibility to reverse the axis it would be nice.

**Comment by Pipshag** [comment]
Closing this since OctoPrint has the option to reverse axis built in. Go in under Profile Settings and reverse it there!

**Comment by MoonshineSG** [comment]
was about to say the same...

**Comment by Pipshag** [comment]
Thought I'd put it up so there's an answer to the question I posted, in case anybody searches the git later on.

**Comment by MoonshineSG** [comment]
maybe the begining of an FAQ :D
