### ISSUE TITLE
REQUEST notification on M600 command - Filament change

### ISSUE THREAD

**Issue by AMFkuna** [MoonshineSG/OctoPrint-Mobile#70]
Hi,
Can You implement M600 notification please?

On colour change command.

Thank You

**Comment by MoonshineSG** [comment]
Can you elaborate? Isn’t that just like “pause”? (I don’t use it, so I am not sure how it works)

**Comment by AMFkuna** [comment]
Look at this page https://www.prusaprinters.org/color-print/

**Comment by AMFkuna** [comment]
I have printers at other room and if I print color object, color change notification will be useful

**Comment by MoonshineSG** [comment]
so... what exactly do you need ? notification for M600 ? thats relatively easy to implement...

**Comment by AMFkuna** [comment]
Yes, if M600 command is present on gcode, send notification "Please change filament." or user text from configuration.

**Comment by MoonshineSG** [comment]
done

**Comment by MoonshineSG** [comment]
update and enjoy!

**Comment by AMFkuna** [comment]
OK 
Now I'm printing, I'll test it asap.

Thank You very much for fast reply.

**Comment by MoonshineSG** [comment]
managed to test it ?

**Comment by AMFkuna** [comment]
Hi, it working perfectly
many thanks
