### ISSUE TITLE
ERROR: Icloud not avalliable

### ISSUE THREAD

**Issue by 1Ghasthunter1** [MoonshineSG/OctoPrint-Mobile#71]
Hello,
Whenever I want to add a second configuration, it always returns with a pop-up window saying:
ERRORL iCloud not avaliable.
Purchasing additional configuration slots requires a valid icloud account. Etc.
How do you fix this?

**Comment by MoonshineSG** [comment]
As the message says, enable iCloud

**Comment by 1Ghasthunter1** [comment]
I’m not too sure what that means or how to do it. I am signed in to my iCloud on the device and everything works with iCloud signed in.

**Comment by MoonshineSG** [comment]
Hmm... maybe you denied access for the app to access iCloud?

**Comment by 1Ghasthunter1** [comment]
Okay, problem solved. I had to turn on iCloud Drive. From there I enabled nautilus. Thanks!

**Comment by 1Ghasthunter1** [comment]
Im using the iphone XR on ios 12.1.1 beta. But enabling that gave me control over the apps
