### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by treflip** [MoonshineSG/OctoPrint-Mobile#75]
Where else to post feature requests?

I hate landscape mode for my 7+. It's hard to hold the phone with one hand and select things this way. I almost drop my phone all the time (do you know how much these screen costs lol!)

I read you force this option to show all the stuff. I understand that but I have not bought this app yet. It may be easier than the web app but I am not sure I will like it now that I found that out.

Will you consider making a portrait mode option? I would very much like that better than landscape!

Thanks!

**Comment by MoonshineSG** [comment]
sorry, unlikely that portrait will be made available...

**Comment by treflip** [comment]
Understood. Thank you

Sent from my iPhone

On Apr 22, 2019, at 1:21 AM, ǝuıɥsuooɯ <notifications@github.com> wrote:

sorry, unlikely that portrait will be made available...
