### ISSUE TITLE
Code 403 issue

### ISSUE THREAD

**Issue by OutspokenPlanet** [MoonshineSG/OctoPrint-Mobile#76]
Recently updated the stretch light installs on my four separate pi servers, and now receiving the message
"The configured URL does not point to a running instance of OctoPrint with the plugin "Nautilus" installed. [code 403]"

I've restarted all of my network infrastructure, and bypassed my haproxy server, all four instances return the same error.

OctoPrint 1.3.11 running on OctoPi 0.16.0 - on one machine
OctoPrint 1.3.11 running on OctoPi 0.15.1 - on three machines
Nautilus (1.24) - all machines

Is there any further info I can give you to help?

**Comment by keithellis74** [comment]
Yep, I’m getting the same message after updating OctoPrint to 1.13.11

Keith Ellis

**Comment by MoonshineSG** [comment]
I will upgrade, investigate and get back to you with a fix in a couple of days

**Comment by MoonshineSG** [comment]
OK... I updated to 1.3.11 and using the latest Nautilus (v 1.24) and there's no problem with it... 

In this case I will need some logs from your side to see if there are any error messages and some more info regarding your setup. 
Are you using anonimous login or you have a user created? 
A list of plugins to see if there could be any conflicts. 
If you go to the Octoprint Settings page do you see Nautilus preferences page ? (meaning the plugin is loaded) 

waiting for your info

**Comment by keithellis74** [comment]
Mine worked initially, try rebooting.  I’ll get the info requested to you when I get a chance. Thank you.

Keith Ellis

**Comment by MoonshineSG** [comment]
seams to be related to ForceLogin plugin...(if yiou disbale that, it's all good!) 
 I'll contact the developer (of OctoPrint) and work out a solution...

**Comment by MoonshineSG** [comment]
a fix is with Apple for review. Should be out as soon as is approved.

**Comment by MoonshineSG** [comment]
fix coming soon. pending apple approval.

**Comment by nevergitithub** [comment]
Hi. I am an absolute beginner. After installing the latest version of Nautilus and Octoprint a couple of days ago, I’m getting the same message. No mods or other plugins are installed than Nautilus. I wil check the ForceLogin this evening.

**Comment by MoonshineSG** [comment]
It’s a bug in octoprint but a workaround fix has been submitted to apple... give it a couple of day , max...

**Comment by MoonshineSG** [comment]
The update is out. Upgrade to the latest - v2.1.8 - and the problem will be gone. Thanks.

**Comment by keithellis74** [comment]
Seems to be fixed, thank you.

Keith Ellis

**Comment by OutspokenPlanet** [comment]
Awesome job, thank you

**Comment by nevergitithub** [comment]
Works fine now. Thank‘s a lot.
