### ISSUE TITLE
Nautilus app currently not available in your coutry

### ISSUE THREAD

**Issue by sajovicd** [MoonshineSG/OctoPrint-Mobile#78]
Hello,

Just try to install Nautilus app on Iphone 11 and I always got error "App is not available in your country." 
I live in Slovenia / Europe. But I change to US store and then I got error "app is not available in US store"

Any help?

**Comment by MoonshineSG** [comment]
i removed it from appstore as i had no time to keep it updated and many other apps are now available. when i made this there was nothing that allowed a decent octoprint UI on a smart phone 
I'll probably open up the source , but you'll need a developer account to install it on your phone

**Comment by keithellis74** [comment]
That’s a shame. I really like this app. I’ll have to make sure I have it backed up.
Thanks for all your efforts in this app.
Good luck.

Keith Ellis

**Comment by MoonshineSG** [comment]
many chnages on the apple side and very weak sales :D 
I'm glad ot hear you like it, but sadly, no time to keep it up to date...
