### ISSUE TITLE
Snap Temperature settings

### ISSUE THREAD

**Issue by Pipshag** [MoonshineSG/OctoPrint-Mobile#8]
**Temperature settings should snap**
It's quite difficult to get the correct temperature to preheat quickly. The sliders should snap easier to the preset intervals.

It would also be good to have an array of values for the temperature sliders that we utilize and that's configurable from settings.ini. This would make it easy to set up your own temp sliders, including having one for cleaning the nozzle, doing cold pulls. Would also make it possible (while keeping down the risks for people without firmware safety) to preheat to temperatures required for PC-ABS from the app.

**Comment by MoonshineSG** [comment]
"array of values for the temperature sliders" sound like a good aproach.

**Comment by MoonshineSG** [comment]
see https://github.com/MoonshineSG/OctoPrint-Mobile/releases/tag/1.5

**Comment by Pipshag** [comment]
Thanks!

**Comment by MoonshineSG** [comment]
let me know how it works.
